namaLengkap=input ("Nama Lengkap : ")
namaPanggilan=input ("Nama Panggilan : ")
npm=input ("masukan NPM : ")
tempatLahir=input ("Masukan Tanggal Lahir : ")
tanggalLahir=input ("Maasukan Tanggal Lahir : ")
umur=input ("masukan Umur Anda : ")
telepon=input ("Masukan Nomor Telepon : ")
alamat=input ("Masukan alamat : ")
print ("----------Biodata Diri Mahasiswa----------")
print("Hello")
print("My name is", namaLengkap, "But you can call me", namaPanggilan, "My NPM is", npm, "I was born in", tempatLahir, "My date of birth", tanggalLahir, "My age is", umur, "My phone number", telepon, "My address is", alamat)
print("thanks")
print("====================")
